
export const CAPA_QUESTIONS = {
  "Pre-Analytical": {
    "Vein puncture failure": [
      "Was the patient properly identified before sample collection?",
      "Was appropriate vein selection performed?",
      "Was the tourniquet applied correctly?",
      "Was proper needle gauge used?",
      "Was the phlebotomist adequately trained?",
      "Were hand hygiene protocols followed?",
      "Was patient positioning appropriate?",
      "Was adequate lighting available?",
      "Were multiple puncture attempts documented?",
      "Was patient comfort considered?",
      "Were alternative collection sites evaluated?",
      "Was supervisor notified of difficulty?",
      "Was equipment condition checked before use?",
      "Were manufacturer instructions followed?",
      "Was incident reported immediately?",
      "Was patient informed appropriately?",
      "Were safety protocols maintained?",
      "Was proper disposal of materials done?",
      "Was documentation completed accurately?",
      "Were corrective measures implemented?"
    ],
    "Typographic error": [
      "Was double-verification performed before data entry?",
      "Was source document legible?",
      "Were standardized abbreviations used?",
      "Was adequate lighting available for reading?",
      "Was staff fatigue a contributing factor?",
      "Were interruptions during data entry minimized?",
      "Was proofreading conducted before finalization?",
      "Were similar-looking values cross-checked?",
      "Was electronic verification system utilized?",
      "Were training records up to date?",
      "Was workload manageable during the shift?",
      "Were ergonomic factors considered?",
      "Was the error detected through routine checks?",
      "Were affected reports recalled promptly?",
      "Was the clinician notified immediately?",
      "Was root cause identified clearly?",
      "Were preventive barriers established?",
      "Was staff counseling provided?",
      "Were standard operating procedures reviewed?",
      "Was the incident logged appropriately?"
    ],
    "Wrong sample identification": [
      "Were two patient identifiers used?",
      "Was verbal confirmation obtained from patient?",
      "Were labels applied at bedside/collection site?",
      "Was barcode scanning system operational?",
      "Were look-alike patient names flagged?",
      "Was positive patient identification protocol followed?",
      "Were wristbands checked before collection?",
      "Was collection time documented accurately?",
      "Were all tubes labeled before leaving patient?",
      "Was handwriting legible on labels?",
      "Were pre-printed labels verified?",
      "Was electronic patient matching confirmed?",
      "Were similar patient names double-checked?",
      "Was staff properly trained on identification?",
      "Were errors detected before analysis?",
      "Was the correct sample retrieved?",
      "Were affected samples rejected?",
      "Was recollection performed if needed?",
      "Were all stakeholders notified?",
      "Was the incident investigated thoroughly?"
    ],
    "Incomplete form": [
      "Was the requisition form completely filled?",
      "Were all mandatory fields marked clearly?",
      "Was clinical information provided adequately?",
      "Was patient demographics verified?",
      "Were test codes entered correctly?",
      "Was requesting physician information complete?",
      "Was sample collection time documented?",
      "Were special handling instructions noted?",
      "Was urgency level specified?",
      "Were billing details completed?",
      "Was insurance information provided?",
      "Were consent forms attached if required?",
      "Was form legibility acceptable?",
      "Were abbreviations standardized?",
      "Was electronic order system functional?",
      "Were incomplete forms flagged immediately?",
      "Was requesting department contacted for clarification?",
      "Were delays in processing documented?",
      "Was staff trained on form completion?",
      "Were process improvements implemented?"
    ],
    "Sample labeling error": [
      "Was sample labeled at point of collection?",
      "Were all required identifiers on label?",
      "Was label securely attached to tube?",
      "Was label information legible?",
      "Were barcode labels printed correctly?",
      "Was collection date and time on label?",
      "Were collector initials on label?",
      "Was sample type clearly indicated?",
      "Were tube numbers sequential?",
      "Was label placed correctly on tube?",
      "Were multiple samples differentiated?",
      "Was label waterproof and smudge-proof?",
      "Were pre-printed labels verified?",
      "Was mislabeling detected before analysis?",
      "Were affected samples quarantined?",
      "Was recollection required?",
      "Were clinicians notified promptly?",
      "Was root cause analysis performed?",
      "Were labeling procedures reinforced?",
      "Was quality indicator monitored?"
    ]
  },
  "Analytical": {
    "Wrong sample processed": [
      "Was sample verification performed before processing?",
      "Was barcode scanning system operational?",
      "Were sample identifiers cross-checked?",
      "Was chain of custody maintained?",
      "Were samples processed in correct sequence?",
      "Was rack position verified?",
      "Were look-alike samples segregated?",
      "Was manual entry error involved?",
      "Were sample tubes distinctive?",
      "Was processing documented accurately?",
      "Was error detected before result release?",
      "Were affected results quarantined?",
      "Was correct sample reanalyzed?",
      "Were clinicians notified immediately?",
      "Was patient safety assessed?",
      "Were SOPs followed correctly?",
      "Was staff training adequate?",
      "Were system controls adequate?",
      "Was incident investigation thorough?",
      "Were preventive measures implemented?"
    ],
    "Random error": [
      "Was error detected through QC monitoring?",
      "Were repeat measurements performed?",
      "Was result reproducibility acceptable?",
      "Were pipetting techniques correct?",
      "Was sample mixing adequate?",
      "Were reagent volumes accurate?",
      "Was temperature control maintained?",
      "Were timing intervals precise?",
      "Was instrument calibration current?",
      "Were environmental conditions stable?",
      "Was operator technique consistent?",
      "Were consumables quality verified?",
      "Was statistical variation within limits?",
      "Were outliers investigated?",
      "Was trend analysis performed?",
      "Were acceptance criteria defined?",
      "Was result correlation checked?",
      "Were delta checks performed?",
      "Was clinical correlation assessed?",
      "Were corrective actions effective?"
    ],
    "Systematic error": [
      "Was calibration performed correctly?",
      "Were calibrators within specification?",
      "Was linearity verified?",
      "Were reagent lots changed recently?",
      "Was instrument drift observed?",
      "Were environmental conditions optimal?",
      "Was systematic bias calculated?",
      "Were all samples affected?",
      "Was error direction consistent?",
      "Were multiple runs affected?",
      "Was method comparison performed?",
      "Were reference values validated?",
      "Was proficiency testing reviewed?",
      "Were historical trends analyzed?",
      "Was manufacturer contacted?",
      "Were service records reviewed?",
      "Was recalibration performed?",
      "Were affected results corrected?",
      "Were clinicians notified?",
      "Was long-term monitoring established?"
    ],
    "IQC failure": [
      "Were QC materials stored at correct temperature?",
      "Was QC performed before patient sample analysis?",
      "Were QC values within acceptable range?",
      "Was the correct QC lot number used?",
      "Were reagents within expiration date?",
      "Was instrument calibration current?",
      "Were Westgard rules applied correctly?",
      "Was QC data trended and reviewed?",
      "Were corrective actions taken before reporting?",
      "Was the QC failure investigated immediately?",
      "Were patient samples held until resolution?",
      "Was repeat QC performed after correction?",
      "Were all affected batches identified?",
      "Was supervisor notified of QC failure?",
      "Were manufacturer support contacted if needed?",
      "Was documentation completed thoroughly?",
      "Were trends analyzed for systemic issues?",
      "Was staff training adequate?",
      "Were SOPs followed correctly?",
      "Was the failure reported to quality team?"
    ],
    "EQAS failure": [
      "Was EQAS sample handled per guidelines?",
      "Was testing performed by qualified personnel?",
      "Was the same method used as routine testing?",
      "Were EQAS results submitted on time?",
      "Was peer group selection appropriate?",
      "Were unacceptable results investigated?",
      "Was root cause analysis performed?",
      "Were corrective actions implemented?",
      "Was repeat EQAS sample analyzed?",
      "Were internal QC trends reviewed?",
      "Was instrument performance evaluated?",
      "Were reagent lots checked?",
      "Was calibration verified?",
      "Were patient samples affected identified?",
      "Was clinical impact assessed?",
      "Were clinicians notified if needed?",
      "Was training provided to staff?",
      "Were SOPs updated as needed?",
      "Was external provider consulted?",
      "Was follow-up EQAS performance monitored?"
    ]
  },
  "Post-Analytical": {
    "Printing error": [
      "Was printer functionality checked before use?",
      "Were print settings configured correctly?",
      "Was paper quality adequate?",
      "Was toner/ink level sufficient?",
      "Were report templates up to date?",
      "Was print alignment correct?",
      "Were all results printed completely?",
      "Was font size and style appropriate?",
      "Were barcodes scannable?",
      "Were graphs and charts clear?",
      "Was print quality verified?",
      "Were duplicate prints avoided?",
      "Was correct report version printed?",
      "Were confidential reports secured?",
      "Was printer maintenance current?",
      "Were print errors detected immediately?",
      "Was reprint performed correctly?",
      "Were affected reports recalled?",
      "Was incident documented?",
      "Were preventive measures implemented?"
    ],
    "Urgent sample report": [
      "Was sample marked as urgent on receipt?",
      "Was priority processing initiated immediately?",
      "Were staff members alerted about urgency?",
      "Was processing time monitored?",
      "Were delays documented and justified?",
      "Was result verification expedited?",
      "Was critical value protocol followed?",
      "Was direct communication with clinician done?",
      "Was verbal report given if needed?",
      "Was time of notification recorded?",
      "Was written report sent promptly?",
      "Was urgent TAT target met?",
      "Were bottlenecks identified?",
      "Was escalation process followed?",
      "Were resources allocated appropriately?",
      "Was patient outcome monitored?",
      "Was feedback received from clinician?",
      "Were process improvements identified?",
      "Was staff performance adequate?",
      "Was urgent protocol effective?"
    ],
    "Critical value reporting": [
      "Was critical value identified immediately?",
      "Were critical limits properly defined?",
      "Was result verified before reporting?",
      "Was clinician contacted directly?",
      "Was read-back verification performed?",
      "Was time of notification documented?",
      "Was recipient name recorded?",
      "Was clinical context considered?",
      "Were multiple attempts made if needed?",
      "Was escalation protocol followed?",
      "Was patient location confirmed?",
      "Was urgency level communicated?",
      "Was written report sent immediately?",
      "Was critical value flagged on report?",
      "Was follow-up sample requested?",
      "Was patient outcome tracked?",
      "Were notification delays investigated?",
      "Was policy compliance monitored?",
      "Were staff trained adequately?",
      "Was process effectiveness evaluated?"
    ],
    "Turnaround time (TAT)": [
      "Was sample received in lab within expected time?",
      "Were pre-analytical delays documented?",
      "Was sample priority correctly identified?",
      "Were urgent samples processed immediately?",
      "Was analyzer throughput adequate?",
      "Were staff levels appropriate for workload?",
      "Were technical issues causing delays?",
      "Was result verification prompt?",
      "Were critical values reported immediately?",
      "Was report generation timely?",
      "Were communication systems functional?",
      "Were transport delays identified?",
      "Was TAT monitored continuously?",
      "Were bottlenecks in workflow identified?",
      "Was staff training adequate?",
      "Were equipment breakdowns a factor?",
      "Was reagent availability ensured?",
      "Were quality checks causing delays?",
      "Was clinical urgency communicated?",
      "Were improvement actions implemented?"
    ],
    "Improper report dispatch": [
      "Was report destination verified before dispatch?",
      "Were recipient details confirmed?",
      "Was correct delivery method used?",
      "Was report confidentiality maintained?",
      "Were reports sealed properly?",
      "Was dispatch tracking system used?",
      "Were electronic reports encrypted?",
      "Was fax number verified before sending?",
      "Were email addresses correct?",
      "Was delivery confirmation obtained?",
      "Were urgent reports flagged?",
      "Was dispatch timing appropriate?",
      "Were multiple reports organized correctly?",
      "Was patient identification verified?",
      "Were reports complete before dispatch?",
      "Was wrong delivery detected promptly?",
      "Were affected parties notified?",
      "Was correct report resent?",
      "Was incident documented thoroughly?",
      "Were dispatch procedures reviewed?"
    ]
  }
};

// Export default for easy import
export default CAPA_QUESTIONS;