import { Book, Shield, FileText, ClipboardList } from "lucide-react";

export const DOC_LEVELS = [
  {
    id: "level-1",
    level: 1,
    title: "Quality Manual",
    description: "Strategic governance and policies.",
    icon: Book,
    color: "bg-purple-100 text-purple-600",
    items: [
      { name: "Quality Manual (Master Document)" },
      { name: "Scope of Services & Locations" },
      { name: "Quality Policy & Objectives" },
      { name: "Organizational Structure / Organogram" },
      { name: "QMS Description & Procedure Map" },
    ],
  },
  {
    id: "level-2",
    level: 2,
    title: "Management Procedures",
    description: "System-wide SOPs & policies.",
    icon: Shield,
    color: "bg-blue-100 text-blue-600",
    items: [
      { name: "Document Control Procedure" },
      { name: "Records Management / Retention" },
      { name: "Risk & Opportunity Management" },
      { name: "Nonconformity & CAPA Management" },
      { name: "Complaints Handling" },
      { name: "Internal Audit Procedure" },
      { name: "Management Review (MRM)" },
      { name: "Training & Competence" },
      { name: "Supplier Management" },
      { name: "Equipment & Calibration Management" },
      { name: "IT & LIS Management" },
      { name: "Business Continuity Plan" },
    ],
  },
  {
    id: "level-3",
    level: 3,
    title: "Technical SOPs",
    description: "Step-by-step analytical instructions.",
    icon: FileText,
    color: "bg-teal-100 text-teal-600",
    // Sub-categories handling
    // Sub-categories handling
    items: [
      { name: "Patient Info & Consent" },
      { name: "Sample Collection (Phlebotomy)" },
      { name: "Sample Transport & Reception" },
      { name: "Acceptance & Rejection Criteria" },
      { name: "Haematology SOPs" },
      { name: "Biochemistry SOPs" },
      { name: "Microbiology SOPs" },
      { name: "Method Verification & Validation" },
      { name: "IQC & EQA Procedures" },
      { name: "Result Review & Authorization" },
      { name: "Critical Results Reporting" },
      { name: "Report Issue & Amendment" },
      { name: "Biosafety & PPE" },
      { name: "Waste Disposal" },
      { name: "Environmental Monitoring" },
    ],
  },
  {
    id: "level-4",
    level: 4,
    title: "Forms & Records",
    description: "Logs, checklists, and raw data.",
    icon: ClipboardList,
    color: "bg-slate-100 text-slate-600",
    items: [
      { name: "CAPA Form" },
      { name: "Risk Register" },
      { name: "Audit Checklist" },
      { name: "Complaint Form" },
      { name: "Job Descriptions" },
      { name: "Training Logs" },
      { name: "Competency Assessments" },
      { name: "Test Requisition Forms" },
      { name: "Temperature Logs" },
      { name: "Maintenance Logs" },
      { name: "Calibration Certificates" },
    ],
  },
  {
    id: "level-5",
    level: 5,
    title: "Legal & Statutory Documents",
    description: "Documents ensuring legal identity as per ISO 15189 / NABL.",
    icon: ClipboardList,
    color: "bg-purple-100 text-purple-600",

    items: [
      { name: "Certificate of Incorporation" },
      { name: "LLP Deed with Addendum" },
      { name: "Partnership / Ownership Declaration" },
      { name: "Shop / Partnership Registration Document" },
      { name: "Shop and Establishment Licence" },
      { name: "MPCB Authorization (BMW)" },
      { name: "Clinical Establishment Act Certificate" },
      { name: "Trade / Municipal Licence" },
      { name: "BMW Disposal Agreement" },
      { name: "BMW Collection Records" },
      { name: "Director Appointment Letter" },
      { name: "Director Qualification Certs" },
      { name: "Medical Council / NMC Reg" },
      { name: "Organization PAN Card" },
      { name: "GST Registration Certificate" },
      { name: "Premises Ownership/Rent Agreement" },
      { name: "Fire Safety / Extinguisher AMC" },
      { name: "Electrical Safety Certificate" },
      { name: "Laboratory Layout Plan" },
      { name: "Equipment Purchase Invoices" },
      { name: "AMC / CMC Contracts" },
      { name: "Calibration Certificates" },
      { name: "EQAS / PT Certificates" },
      { name: "Outsourced Test Agreements" },
      { name: "LIS / Software Agreement" },
      { name: "Professional Indemnity Insurance" },
      { name: "Public Liability Insurance" },
      { name: "ESI / Workmen Insurance" },
      { name: "Statutory Compliance Register" },
      { name: "License Renewal Tracker" },
      { name: "Legal Requirement List" },
    ],
  },
  {
    id: "level-6",
    level: 6,
    title: "Others",
    description: "Add the necessary documents as per ISO 15189 / NABL.",
    icon: ClipboardList,
    color: "bg-purple-100 text-purple-600",
    items: [],
  },
];
