export const dummyUSerData = [
  {
    id: 1,
    username: "ecurrin0",
    email: "kaspray0@tmall.com",
    role: "Auditor",
    department: "Radiology",
  },
  {
    id: 2,
    username: "jshackelton1",
    email: "cpyper1@archive.org",
    role: "Laboratory Director",
    department: "Microbiology",
  },
  {
    id: 3,
    username: "gridewood2",
    email: "bverry2@xrea.com",
    role: "Trainer",
    department: "Biochemistry",
  },
  {
    id: 4,
    username: "nreffe3",
    email: "cpottell3@live.com",
    role: "Quality Manager",
    department: "Microbiology",
  },
  {
    id: 5,
    username: "nrosander4",
    email: "lswane4@jigsy.com",
    role: "Laboratory Director",
    department: "Administration",
  },
  {
    id: 6,
    username: "morchart5",
    email: "pvassall5@house.gov",
    role: "Quality Analyst",
    department: "Hematology",
  },
  {
    id: 7,
    username: "ssteger6",
    email: "lcopplestone6@google.fr",
    role: "Quality Manager",
    department: "Hematology",
  },
  {
    id: 8,
    username: "hrogeon7",
    email: "awoolmer7@homestead.com",
    role: "Trainer",
    department: "Biochemistry",
  },
  {
    id: 9,
    username: "wcultcheth8",
    email: "mmarshallsay8@miibeian.gov.cn",
    role: "Trainer",
    department: "Quality Assurance",
  },
  {
    id: 10,
    username: "kdinis9",
    email: "ejeynes9@stanford.edu",
    role: "Quality Analyst",
    department: "Microbiology",
  },
  {
    id: 11,
    username: "jberridgea",
    email: "bscoullera@nymag.com",
    role: "Lab Technician",
    department: "Pathology",
  },
  {
    id: 12,
    username: "ebimsonb",
    email: "ewalbyb@jiathis.com",
    role: "Supervisor",
    department: "Administration",
  },
  {
    id: 13,
    username: "nivashkovc",
    email: "kseeviourc@artisteer.com",
    role: "Lab Technician",
    department: "Microbiology",
  },
  {
    id: 14,
    username: "dhugenind",
    email: "bregglerd@si.edu",
    role: "Lab Technician",
    department: "Microbiology",
  },
  {
    id: 15,
    username: "afontenote",
    email: "mjoulee@epa.gov",
    role: "Laboratory Director",
    department: "Quality Assurance",
  },
  {
    id: 16,
    username: "apymf",
    email: "eraubheimf@google.com.br",
    role: "Supervisor",
    department: "Hematology",
  },
  {
    id: 17,
    username: "bjirig",
    email: "tbonasg@squidoo.com",
    role: "Quality Manager",
    department: "Quality Assurance",
  },
  {
    id: 18,
    username: "mfeldhornh",
    email: "ojuckesh@google.cn",
    role: "Auditor",
    department: "Radiology",
  },
  {
    id: 19,
    username: "krastricki",
    email: "dsweedyi@prweb.com",
    role: "Lab Technician",
    department: "Administration",
  },
  {
    id: 20,
    username: "llaileyj",
    email: "cmaccrackenj@merriam-webster.com",
    role: "Trainer",
    department: "Microbiology",
  },
];
