export const QUALITY_INDICATORS = [
  // --- Pre-Analytical ---
  {
    id: "pre-1",
    name: "Vein puncture failure",
    category: "Pre-Analytical",
    count: 12,
    hasCapa: true,
    capaId: "CAPA-2026-001",
    threshold: 10,
    severity: 3,
    incidents: [
      { date: "2026-01-05", value: 1 },
      { date: "2026-01-29", value: 2 },
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-15", value: 5 },
      { date: "2026-01-21", value: 1 },
      { date: "2026-01-30", value: 2 },
    ],
  },
  {
    id: "pre-2",
    name: "Typographic Error",
    category: "Pre-Analytical",
    count: 5,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "pre-3",
    name: "Wrong sample identification",
    category: "Pre-Analytical",
    count: 3,
    hasCapa: true,
    capaId: "CAPA-2026-015",
    incidents: [],
  },
  {
    id: "pre-4",
    name: "Incomplete form",
    category: "Pre-Analytical",
    count: 8,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-14", value: 1 },
      { date: "2026-01-16", value: 2 },
      { date: "2026-01-25", value: 5 },
    ],
  },
  {
    id: "pre-5",
    name: "Sample Labeling error",
    category: "Pre-Analytical",
    count: 15,
    hasCapa: true,
    capaId: "CAPA-2026-008",
    incidents: [],
  },
  {
    id: "pre-6",
    name: "Inappropriate vial selection",
    category: "Pre-Analytical",
    count: 2,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "pre-7",
    name: "Accidents reported",
    category: "Pre-Analytical",
    count: 1,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-2", value: 2 },
      { date: "2026-01-13", value: 2 },
      { date: "2026-01-14", value: 2 },
      { date: "2026-01-12", value: 2 },
    ],
  },

  // --- Analytical ---
  {
    id: "ana-1",
    name: "Wrong sample processed",
    category: "Analytical",
    count: 0,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "ana-2",
    name: "Random error",
    category: "Analytical",
    count: 4,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-13", value: 1 },
      { date: "2026-01-17", value: 4 },
      { date: "2026-01-18", value: 6 },
    ],
  },
  {
    id: "ana-3",
    name: "Systematic error",
    category: "Analytical",
    count: 1,
    hasCapa: true,
    capaId: "CAPA-2026-022",
    incidents: [],
  },
  {
    id: "ana-4",
    name: "IQC Failure",
    category: "Analytical",
    count: 9,
    hasCapa: true,
    capaId: "CAPA-2026-005",
    threshold: 5,
    severity: 5,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-23", value: 1 },
      { date: "2026-01-19", value: 1 },
      { date: "2026-01-20", value: 9 },
    ],
  },
  {
    id: "ana-5",
    name: "EQAS Failure",
    category: "Analytical",
    count: 2,
    hasCapa: true,
    capaId: "CAPA-2026-012",
    incidents: [],
  },
  {
    id: "ana-6",
    name: "Sample Re-assay",
    category: "Analytical",
    count: 22,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-9", value: 2 },
      { date: "2026-01-04", value: 2 },
      { date: "2026-01-05", value: 2 },
      { date: "2026-01-06", value: 2 },
    ],
  },

  // --- Post-Analytical ---
  {
    id: "post-1",
    name: "Printing Error",
    category: "Post-Analytical",
    count: 6,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-31", value: 2 },
      { date: "2026-01-21", value: 2 },
      { date: "2026-01-22", value: 2 },
    ],
  },
  {
    id: "post-2",
    name: "Urgent sample report",
    category: "Post-Analytical",
    count: 45,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "post-3",
    name: "Critical Value Reporting",
    category: "Post-Analytical",
    count: 120,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "post-4",
    name: "Turnaround time (TAT)",
    category: "Post-Analytical",
    count: 14,
    hasCapa: true,
    capaId: "CAPA-2026-030",
    threshold: 15,
    severity: 4,
    incidents: [],
  },
  {
    id: "post-5",
    name: "Improper report dispatch",
    category: "Post-Analytical",
    count: 3,
    hasCapa: false,
    incidents: [],
  },
  {
    id: "post-6",
    name: "Report delivery Time",
    category: "Post-Analytical",
    count: 7,
    hasCapa: false,
    incidents: [
      { date: "2026-01-12", value: 2 },
      { date: "2026-01-12", value: 5 },
      { date: "2026-01-16", value: 2 },
      { date: "2026-01-14", value: 6 },
      { date: "2026-01-18", value: 2 },
    ],
  },
];

export const CATEGORIES = ["Pre-Analytical", "Analytical", "Post-Analytical"];
